### ISSUE TITLE
is the proyect ended?

### ISSUE THREAD

**Issue by alavaelian** [microsounds/kagami#2]
i come back after a while and have seen not recent commints why is that?
saludos :+1:

**Comment by microsounds** [comment]
I haven't felt the need to add more features, I've been getting away with calling shell scripts from within `.kagami/macros` whenever I need to generate static webpage content that isn't covered by kagami features, and most of these scripts are so specific to my needs, really petty leech behavior like scraping other websites and updating inline JavaScript to reflect changes on those websites is stuff that I feel doesnt really belong in a general purpose static microblogging tool, I would be peppering kagami's environment variables with dozens of ENV_VARS if that were the case and bloat up the scope of this tool faster than I care to describe changes.

It's feature complete for now, and if my needs change I'll start adding more features.

**Comment by alavaelian** [comment]
oh thanks for answer then.
